name 'rm_tree'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures rm_tree'
long_description 'Installs/Configures rm_tree'
version '0.1.0'
