name 'dyn_cookbook_apache2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures dyn_cookbook_apache2'
long_description 'Installs/Configures dyn_cookbook_apache2'
version '0.1.0'
